export const emojiList = [
  { id: 1, emoji: '😀', name: 'Grinning Face' },
  { id: 2, emoji: '😃', name: 'Grinning Face with Big Eyes' },
  { id: 3, emoji: '😄', name: 'Grinning Face with Smiling Eyes' },
  { id: 4, emoji: '😁', name: 'Beaming Face with Smiling Eyes' },
  { id: 5, emoji: '😆', name: 'Grinning Squinting Face' },
  { id: 6, emoji: '😅', name: 'Grinning Face with Sweat' },
  { id: 7, emoji: '🤣', name: 'Rolling on the Floor Laughing' },
  { id: 8, emoji: '😊', name: 'Smiling Face with Smiling Eyes' },
  { id: 9, emoji: '😎', name: 'Smiling Face with Sunglasses' },
  { id: 10, emoji: '🙂', name: 'Slightly Smiling Face' },
  { id: 11, emoji: '😍', name: 'Smiling Face with Heart-Eyes' },
  { id: 12, emoji: '🤩', name: 'Star-Struck' },
  { id: 13, emoji: '😘', name: 'Face Blowing a Kiss' },
  { id: 14, emoji: '😚', name: 'Kissing Face with Closed Eyes' },
  { id: 15, emoji: '😉', name: 'Winking Face' },
  { id: 16, emoji: '🥰', name: 'Smiling Face with Hearts' },
  { id: 17, emoji: '😇', name: 'Smiling Face with Halo' },
  { id: 18, emoji: '😌', name: 'Relieved Face' },
  { id: 19, emoji: '😋', name: 'Face Savoring Food' },
  { id: 20, emoji: '😜', name: 'Winking Face with Tongue' },
  { id: 21, emoji: '🤪', name: 'Zany Face' },
  { id: 22, emoji: '😛', name: 'Face with Tongue' },
  { id: 23, emoji: '😎', name: 'Smiling Face with Sunglasses' },
  { id: 24, emoji: '😏', name: 'Smirking Face' },
  { id: 25, emoji: '😒', name: 'Unamused Face' },
  { id: 26, emoji: '😞', name: 'Disappointed Face' },
  { id: 27, emoji: '😔', name: 'Pensive Face' },
  { id: 28, emoji: '😕', name: 'Confused Face' },
  { id: 29, emoji: '🙃', name: 'Upside-Down Face' },
  { id: 30, emoji: '🤨', name: 'Face with Raised Eyebrow' },
  { id: 31, emoji: '😳', name: 'Flushed Face' },
  { id: 32, emoji: '😬', name: 'Grimacing Face' },
  { id: 33, emoji: '😧', name: 'Anguished Face' },
  { id: 34, emoji: '😮', name: 'Face with Open Mouth' },
  { id: 35, emoji: '😯', name: 'Hushed Face' },
  { id: 36, emoji: '😶', name: 'Face Without Mouth' },
  { id: 37, emoji: '😑', name: 'Expressionless Face' },
  { id: 38, emoji: '🤐', name: 'Zipper-Mouth Face' },
  { id: 39, emoji: '🙄', name: 'Face with Rolling Eyes' },
  { id: 40, emoji: '😪', name: 'Sleepy Face' },
  { id: 41, emoji: '😴', name: 'Sleeping Face' },
  { id: 42, emoji: '😫', name: 'Tired Face' },
  { id: 43, emoji: '😤', name: 'Face with Steam From Nose' },
  { id: 44, emoji: '😡', name: 'Pouting Face' },
  { id: 45, emoji: '😠', name: 'Angry Face' },
  { id: 46, emoji: '🤬', name: 'Face with Symbols on Mouth' },
  { id: 47, emoji: '👍', name: 'Thumbs Up' },
  { id: 48, emoji: '👎', name: 'Thumbs Down' },
  { id: 49, emoji: '👌', name: 'OK Hand' },
  { id: 50, emoji: '👊', name: 'Fist Bump' },
  // Add more emojis here
];
